const ERROR_CODE_INCORRECT_DATA = 400;
const ERROR_CODE_MISSING_ENTRY = 404;
const ERROR_CODE_OTHER = 500;

module.exports = { ERROR_CODE_INCORRECT_DATA, ERROR_CODE_MISSING_ENTRY, ERROR_CODE_OTHER };
